version: '2.1'

services:
  db:
    image: mariadb
    restart: always
    healthcheck:
      test: "exit 0"
    volumes:
      - "./db-entrypoint:/docker-entrypoint-initdb.d"
      - "./db-data:/var/lib/mysql"
    ports:
      - 8925:3306
    env_file: ./db.env

  campfyre-api:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3973:3973
      - 3974:3974
    env_file: ./api.env
